language: python
cache: pip
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- nightly
node_js:
  - "node"
git:
  depth: 3
notifications:
  email:
    on_success: never
install:
  - pip install -r requirements.txt
  - npm install -g firebase-tools
script: python run.py build
after_success:
  - test TRAVIS_PYTHON_VERSION = "3.6" && echo "Hi!"
addons:
  artifacts:
    s3_region: us-west-2
    bucket: beta-uwaterloo-xyz
    paths:
    - build/index.html
